CREATE TABLE User(
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	PRIMARY KEY (Email)
);

CREATE TABLE GeneralUser(
	Email VARCHAR(255) NOT NULL, 
	QuizzesTaken INTEGER NOT NULL,
	FOREIGN KEY (Email) REFERENCES User(Email),
	PRIMARY KEY (Email)
);

CREATE TABLE Creator(
	Email VARCHAR(255) NOT NULL, 
	QuizzesMade INTEGER NOT NULL,
	FOREIGN KEY (Email) REFERENCES User(Email),
	PRIMARY KEY (Email)
);

CREATE TABLE Quiz(
	ID INTEGER NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Title VARCHAR(255) NOT NULL,
	Created TIMESTAMP NOT NULL,
	FOREIGN KEY (Email) REFERENCES Creator(Email),
	PRIMARY KEY (ID)
);

CREATE TABLE Question(
	QuizID INTEGER NOT NULL,
	ID INTEGER NOT NULL,
	Description TEXT NOT NULL,
	Answer CHARACTER(1) NOT NULL,
	FOREIGN KEY (QuizID) REFERENCES Quiz(ID)
	PRIMARY KEY (QuizID, ID)
);

CREATE TABLE QuestionOption(
	QuizID INTEGER NOT NULL,
	QuestionID INTEGER NOT NULL,
	Description TEXT NOT NULL,
	Option CHARACTER(1) NOT NULL,
	FOREIGN KEY (QuizID) REFERENCES Question(QuizID),
	FOREIGN KEY (QuestionID) REFERENCES Question(ID),
	PRIMARY KEY (QuizID, QuestionID, Option)
);

CREATE TABLE UserQuizzes(
	QuizID INTEGER NOT NULL,
	UserEmail INTEGER NOT NULL,
	Completed BOOLEAN NOT NULL,
	Score INTEGER,
	FOREIGN KEY (QuizID) REFERENCES Quiz(ID),
	FOREIGN KEY (UserEmail) REFERENCES GeneralUser(Email),
	PRIMARY KEY (QuizID, UserEmail)
);