CREATE TABLE Users(
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY (email)
);

CREATE TABLE Quiz(
	ID INTEGER NOT NULL,
	email VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	CONSTRAINT FK_User FOREIGN KEY (email) REFERENCES User(email),
	PRIMARY KEY (ID, email);
);